# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1siT9r9MEDxzal74yTtrbADQx--JSSk0f
"""

from sentence_transformers import SentenceTransformer
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd
import matplotlib.pyplot as plt

# 1. Load model
model = SentenceTransformer("google/embeddinggemma-300M")

# 2. Example datasets (replace with your trivia questions)
science_questions = pd.read_csv(r'evaluating_LC\datasets\simple_qa_st.csv')["question"].tolist()
art_questions = pd.read_csv(r'evaluating_LC\datasets\simple_qa_art.csv')["question"].tolist()
geography_questions = pd.read_csv(r'evaluating_LC\datasets\simple_qa_geography.csv')["question"].tolist()


# 3. Encode each dataset
science_emb = model.encode(science_questions)
art_emb = model.encode(art_questions)
geo_emb = model.encode(geography_questions)

# 4. Aggregate (mean embedding per domain)
science_vec = np.mean(science_emb, axis=0)
art_vec = np.mean(art_emb, axis=0)
geo_vec = np.mean(geo_emb, axis=0)

# 5. Compute similarities
def sim(a, b):
    return cosine_similarity([a], [b])[0][0]

st_st_similarity = 1
st_art_similarity = sim(science_vec, art_vec)
print("Science ↔ Art:", st_art_similarity)
st_geo_similarity = sim(science_vec, geo_vec)
print("Science ↔ Geography:", st_geo_similarity)
art_geo_similarity = sim(art_vec, geo_vec)
print("Art ↔ Geography:", art_geo_similarity)

#Science ↔ Art: 0.8247992
#Science ↔ Geography: 0.70708644
#Art ↔ Geography: 0.68909246

# Example data (replace with yours)
similarity = np.array([st_art_similarity, st_geo_similarity, st_st_similarity]*2) # duplicate for both models
domains = [ "Art", "Geography","Tech"]

# Base LC #4b art geo st 12b art geo st
calib_base = np.array([0.8051, 0.7683, 0.7809, 0.7839, 0.7642, 0.7676])

# Base LC+
calib_unc = np.array([0.7040, 0.6915, 0.7604, 0.7739, 0.7401, 0.7268])

# Fine-tuned model
calib_ft = np.array([0.7620, 0.7491, 0.7827, 0.7941, 0.7475, 0.7721])

# Plot
plt.figure()
marker_size = [200, 200, 200, 500, 500, 500]

# Base model (circles)
plt.scatter(similarity, calib_base, marker='o', label='LC', alpha=0.5, s=marker_size)

# Base model (circles)
plt.scatter(similarity, calib_unc, marker='o', label='LC+', alpha=0.5, s=marker_size)

# Fine-tuned model (triangles)
plt.scatter(similarity, calib_ft, marker='o', label='Fine-tuned', alpha=0.5, s=marker_size)

  # [0,1,2]

#plt.scatter(x, calib_base, marker='o', label='Base')
#plt.scatter(x, calib_ft, marker='^', label='Fine-tuned')
plt.margins(x=0.1, y=0.1)

for i, domain in enumerate(domains):
    plt.annotate(
        domain,
        (similarity[i], calib_ft[i]),
        textcoords="offset points",
        xytext=(5,5),
        fontsize=11
    )

# Labels
plt.xlabel("Domain Similarity")
plt.ylabel("Calibration Error")
plt.title("Calibration vs Domain Similarity")


plt.legend(markerscale=0.5, loc='lower right') # Added markerscale to make legend markers smaller
plt.savefig("calibration_vs_domain_similarity.png")
plt.show()

# Example data (replace with yours)
similarity = np.array([st_art_similarity, st_geo_similarity, st_st_similarity]*2) # duplicate for both models
domains = [ "Art", "Geography","Tech"]

# Base LC  "Art", "Geography","Tech"
calib_base = np.array([0.1212, 0.4141, 0.4818, 0.6615, 0.4758, 0.4989])

# Base LC+
calib_unc = np.array([0.6084, 0.3242, 0.6071, 0.5510, 0.6323, 0.4562])

# Fine-tuned model
calib_ft = np.array([0.4337, 0.6126, 0.4124 , 0.7010, 0.7092, 0.5010])

# Plot
plt.figure()
marker_size = [200, 200, 200, 500, 500, 500]

# Base model (circles)
plt.scatter(similarity, calib_base, marker='o', label='LC', alpha=0.5, s=marker_size)

# Base model (circles)
plt.scatter(similarity, calib_unc, marker='o', label='LC+', alpha=0.5, s=marker_size)

# Fine-tuned model (triangles)
plt.scatter(similarity, calib_ft, marker='o', label='Fine-tuned', alpha=0.5, s=marker_size)

  # [0,1,2]

#plt.scatter(x, calib_base, marker='o', label='Base')
#plt.scatter(x, calib_ft, marker='^', label='Fine-tuned')
plt.margins(x=0.1, y=0.1)

for i, domain in enumerate(domains):
    plt.annotate(
        domain,
        (similarity[i], calib_ft[i]),
        textcoords="offset points",
        xytext=(5,5),
        fontsize=11
    )

# Labels
plt.xlabel("Domain Similarity")
plt.ylabel("AUROC")
plt.title("Discrimination vs Domain Similarity")


plt.legend(markerscale=0.5, loc='lower right') # Added markerscale to make legend markers smaller
plt.savefig("discriminability_vs_domain_similarity.png")
plt.show()